services:
  chiroone-backend:
    build: .
    container_name: chiroone-backend
    restart: always
    ports:
      - "3009:3009"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NODE_TLS_REJECT_UNAUTHORIZED=0
